export { default as Logo } from '../../components/Logo.vue'
export { default as VuetifyLogo } from '../../components/VuetifyLogo.vue'
export { default as Test } from '../../components/test.vue'
export { default as AuthCloseAccount } from '../../components/auth/close-account.vue'
export { default as AuthLoginSugestion } from '../../components/auth/login-sugestion.vue'
export { default as AuthRegisterSugestion } from '../../components/auth/register-sugestion.vue'
export { default as AuthSocialLogin } from '../../components/auth/social-login.vue'
export { default as CarritoPage } from '../../components/carrito/Carrito.page.vue'
export { default as CarritoEditOrder } from '../../components/carrito/editOrder.vue'
export { default as CarritoShoplist } from '../../components/carrito/shoplist.vue'
export { default as Catalogo } from '../../components/catalogo/catalogo.vue'
export { default as CatalogoCategory } from '../../components/catalogo/category.vue'
export { default as CatalogoPortada } from '../../components/catalogo/portada.vue'
export { default as CatalogoPrice } from '../../components/catalogo/price.vue'
export { default as CatalogoProductCard } from '../../components/catalogo/product-card.vue'
export { default as CategoriasCard } from '../../components/categorias/categorias.card.vue'
export { default as Categorias } from '../../components/categorias/categorias.vue'
export { default as CategoryPage } from '../../components/category/Category.page.vue'
export { default as CategoryHomecardCategory } from '../../components/category/homecard.category.vue'
export { default as CommonCsvImport } from '../../components/common/CsvImport.vue'
export { default as CommonInfoRow } from '../../components/common/Info-row.vue'
export { default as CommonModal } from '../../components/common/Modal.vue'
export { default as CommonCanvasUploadResg } from '../../components/common/canvas-upload-resg.vue'
export { default as CommonCanvasUpload } from '../../components/common/canvas-upload.vue'
export { default as CommonChart } from '../../components/common/chart.vue'
export { default as CommonConfigurableBanner } from '../../components/common/configurable-banner.vue'
export { default as CommonCropper } from '../../components/common/cropper.vue'
export { default as CommonImagesModal } from '../../components/common/images-modal.vue'
export { default as CommonLoaderImg } from '../../components/common/loader-img.vue'
export { default as CommonRegisterModal } from '../../components/common/register-modal.vue'
export { default as CommonRibbonTitle } from '../../components/common/ribbon.title.vue'
export { default as CommonSnackbar } from '../../components/common/snackbar.vue'
export { default as Contacto } from '../../components/contacto/Contacto.vue'
export { default as CotizadorPage } from '../../components/cotizador/Cotizador.page.vue'
export { default as CotizadorCardCotizadorProduct } from '../../components/cotizador/card.cotizador.product.vue'
export { default as CotizadorCategoryRow } from '../../components/cotizador/category.row.vue'
export { default as CotizadorHeaderRowMobil } from '../../components/cotizador/header.row.mobil.vue'
export { default as CotizadorHeaderRowWide } from '../../components/cotizador/header.row.wide.vue'
export { default as EncontrarRepuestoPage } from '../../components/encontrar-repuesto/Encontrar-repuesto.page.vue'
export { default as EncuestaPage } from '../../components/encuesta/Encuesta.page.vue'
export { default as HomeBanner } from '../../components/home/Banner.vue'
export { default as HomeBrandsHome } from '../../components/home/BrandsHome.vue'
export { default as HomeFindProduct } from '../../components/home/Find.Product.vue'
export { default as Home } from '../../components/home/Home.vue'
export { default as LayoutLoading } from '../../components/layout/loading.vue'
export { default as LayoutSystemLoading } from '../../components/layout/system-loading.vue'
export { default as LayoutWhatsapp } from '../../components/layout/whatsapp.vue'
export { default as Linktree } from '../../components/linktree/linktree.vue'
export { default as MiCuentaPage } from '../../components/mi-cuenta/miCuenta.page.vue'
export { default as NovedadesPage } from '../../components/novedades/novedades.page.vue'
export { default as OfertasPage } from '../../components/ofertas/Ofertas.page.vue'
export { default as OtrosProductosPageRes } from '../../components/otros-productos/otros-productos.page-res.vue'
export { default as OtrosProductosPage } from '../../components/otros-productos/otros-productos.page.vue'
export { default as Post } from '../../components/post/Post.vue'
export { default as PostSectionsPanel } from '../../components/post/sections-panel.vue'
export { default as ProductPage } from '../../components/product/Product.page.vue'
export { default as ProductCardProduct } from '../../components/product/card.product.vue'
export { default as ProductInfoCardProduct } from '../../components/product/info.card.product.vue'
export { default as ProductPriceCardProduct } from '../../components/product/price.card.product.vue'
export { default as ProductPricetagCardProduct } from '../../components/product/pricetag.card.product.vue'
export { default as ProductShopButton } from '../../components/product/shop-button.vue'
export { default as ResultadosPage } from '../../components/resultados-de-busqueda/resultados.page.vue'
export { default as Tyc } from '../../components/tyc/Tyc.vue'
export { default as Ubicacion } from '../../components/ubicacion/Ubicacion.vue'
export { default as AdminCategorias } from '../../components/admin/categorias/Categorias.vue'
export { default as AdminCategoriasImportarCategorias } from '../../components/admin/categorias/ImportarCategorias.vue'
export { default as AdminCategoriasCategoryImageModal } from '../../components/admin/categorias/category.image-modal.vue'
export { default as AdminCategoriasCategoryRow } from '../../components/admin/categorias/category.row.vue'
export { default as AdminCategoriasCreateCategory } from '../../components/admin/categorias/create.category.vue'
export { default as AdminConfiguraciones } from '../../components/admin/configuraciones/Configuraciones.vue'
export { default as AdminConfiguracionesAppImages } from '../../components/admin/configuraciones/appImages.vue'
export { default as AdminConfiguracionesMinimos } from '../../components/admin/configuraciones/minimos.vue'
export { default as AdminConfiguracionesPdfs } from '../../components/admin/configuraciones/pdfs.vue'
export { default as AdminConfiguracionesRetiro } from '../../components/admin/configuraciones/retiro.vue'
export { default as AdminConfiguracionesSociales } from '../../components/admin/configuraciones/sociales.vue'
export { default as AdminEstadisticasBusquedas } from '../../components/admin/estadisticas/busquedas.vue'
export { default as AdminEstadisticasChart } from '../../components/admin/estadisticas/chart.js'
export { default as AdminEstadisticasEllipseChart } from '../../components/admin/estadisticas/ellipse-chart.js'
export { default as AdminEstadisticasEncuestas } from '../../components/admin/estadisticas/encuestas.vue'
export { default as AdminEstadisticasGraficoDeVentas } from '../../components/admin/estadisticas/grafico-de-ventas.vue'
export { default as AdminEstadisticasMasVendidos } from '../../components/admin/estadisticas/mas-vendidos.vue'
export { default as AdminEstadisticasProductsNoPhotos } from '../../components/admin/estadisticas/products-no-photos.vue'
export { default as AdminEstadisticasProductsUpdateLog } from '../../components/admin/estadisticas/products-update-log.vue'
export { default as AdminEstadisticasTrackEvents } from '../../components/admin/estadisticas/track-events.vue'
export { default as AdminEstadisticasUfos } from '../../components/admin/estadisticas/ufos.vue'
export { default as AdminEstadisticasUrlRepetidos } from '../../components/admin/estadisticas/url-repetidos.vue'
export { default as AdminEstadisticasVentasPorProvincia } from '../../components/admin/estadisticas/ventas-por-provincia.vue'
export { default as AdminImportarRelaciones } from '../../components/admin/importar-relaciones/ImportarRelaciones.vue'
export { default as AdminLayoutMenu } from '../../components/admin/layout/menu.vue'
export { default as AdminLayoutTopNav } from '../../components/admin/layout/top-nav.vue'
export { default as AdminMarcasDeAutosBrands } from '../../components/admin/marcas-de-autos/Brands.vue'
export { default as AdminMarcasDeAutosImportBrands } from '../../components/admin/marcas-de-autos/ImportBrands.vue'
export { default as AdminMarcasDeAutosBrandRow } from '../../components/admin/marcas-de-autos/brand-row.vue'
export { default as AdminMetadataProductRowMetadata } from '../../components/admin/metadata/Product-row.metadata.vue'
export { default as AdminMetadataCategories } from '../../components/admin/metadata/categories.vue'
export { default as AdminMetadataMetaProductRow } from '../../components/admin/metadata/meta.product.row.vue'
export { default as AdminMetadataPages } from '../../components/admin/metadata/pages.vue'
export { default as AdminMetadataProducts } from '../../components/admin/metadata/products.vue'
export { default as AdminModelosDeAutosImportModels } from '../../components/admin/modelos-de-autos/ImportModels.vue'
export { default as AdminModelosDeAutosModels } from '../../components/admin/modelos-de-autos/Models.vue'
export { default as AdminModelosDeAutosModelRow } from '../../components/admin/modelos-de-autos/model-row.vue'
export { default as AdminModelosDeAutosUpdateModal } from '../../components/admin/modelos-de-autos/updateModal.vue'
export { default as AdminOrdersMain } from '../../components/admin/orders/Main.vue'
export { default as AdminOrdersOrder } from '../../components/admin/orders/Order.vue'
export { default as AdminOrdersTable } from '../../components/admin/orders/OrdersTable.vue'
export { default as AdminOrdersLogEditions } from '../../components/admin/orders/log-editions.vue'
export { default as AdminOrdersSelector } from '../../components/admin/orders/selector.vue'
export { default as AdminPostsBlock } from '../../components/admin/posts/block.vue'
export { default as AdminPostsPanel } from '../../components/admin/posts/panel.vue'
export { default as AdminPostsSection } from '../../components/admin/posts/section.vue'
export { default as AdminPostsSections } from '../../components/admin/posts/sections.vue'
export { default as AdminProductosImportProducts } from '../../components/admin/productos/ImportProducts.vue'
export { default as AdminProductosProducts } from '../../components/admin/productos/Products.vue'
export { default as AdminProductosCreateProduct } from '../../components/admin/productos/create.product.vue'
export { default as AdminProductosOrderImagesProducts } from '../../components/admin/productos/orderImages.products.vue'
export { default as AdminProductosPanicButton } from '../../components/admin/productos/panic-button.vue'
export { default as AdminProductosProductImageModal } from '../../components/admin/productos/product.image-modal.vue'
export { default as AdminProductosProductModelsModal } from '../../components/admin/productos/product.models-modal.vue'
export { default as AdminProductosProductModelsRow } from '../../components/admin/productos/product.models-row.vue'
export { default as AdminProductosProductRow } from '../../components/admin/productos/product.row.vue'
export { default as AdminUsuarios } from '../../components/admin/usuarios/Usuarios.vue'
export { default as AdminUsuariosUserModal } from '../../components/admin/usuarios/user.modal.vue'
export { default as LayoutCarritoProductos } from '../../components/layout/carrito/carrito.productos.vue'
export { default as LayoutCategoriesSidePanelCardCategoryPanel } from '../../components/layout/categories-side-panel/card.category.panel.vue'
export { default as LayoutCategoriesSidePanelCategories } from '../../components/layout/categories-side-panel/panel.categories.vue'
export { default as LayoutCategoriesSidePanelResCardCategoryPanel } from '../../components/layout/categories-side-panel-res/card.category.panel.vue'
export { default as LayoutCategoriesSidePanelCategoriesRes } from '../../components/layout/categories-side-panel-res/panel.categories-res.vue'
export { default as LayoutCommonsNavItems } from '../../components/layout/commons/nav-items.vue'
export { default as LayoutFooter } from '../../components/layout/footer/Footer.vue'
export { default as LayoutFooterCategoriesFooter } from '../../components/layout/footer/categories.footer.vue'
export { default as LayoutFooterLogoFooter } from '../../components/layout/footer/logo.footer.vue'
export { default as LayoutFooterMobileFooter } from '../../components/layout/footer/mobile.footer.vue'
export { default as LayoutFooterWebFooter } from '../../components/layout/footer/web.footer.vue'
export { default as LayoutNavMobNav } from '../../components/layout/nav/Mob.nav.vue'
export { default as LayoutNavWideNav } from '../../components/layout/nav/Wide.nav.vue'
export { default as LayoutNavBlackbarTopnav } from '../../components/layout/nav/blackbar.topnav.vue'
export { default as LayoutNavSearchbarNav } from '../../components/layout/nav/searchbar.nav.vue'
export { default as LayoutNavWideNavigationItems } from '../../components/layout/nav/wide.navigation-items.vue'
export { default as ProductPageNotmodProductPage } from '../../components/product/page/notmod.product.page.vue'
export { default as AdminConfiguracionesBannerHome } from '../../components/admin/configuraciones/banner-home/BannerHome.vue'
export { default as AdminConfiguracionesBannerHomeAppimageUpload } from '../../components/admin/configuraciones/banner-home/appimage-upload.vue'
export { default as AdminConfiguracionesHomeMarcas } from '../../components/admin/configuraciones/home-marcas/HomeMarcas.vue'
export { default as AdminConfiguracionesHomeMarcasAppImageRow } from '../../components/admin/configuraciones/home-marcas/appImageRow.vue'
export { default as AdminConfiguracionesHomeMarcasUpload } from '../../components/admin/configuraciones/home-marcas/upload.vue'
export { default as AdminConfiguracionesLinktreeLinkRow } from '../../components/admin/configuraciones/linktree/link-row.vue'
export { default as AdminConfiguracionesLinktree } from '../../components/admin/configuraciones/linktree/linktree.vue'
export { default as AdminConfiguracionesSliderBannerHome } from '../../components/admin/configuraciones/slider-banner-home/SliderBannerHome.vue'
export { default as AdminConfiguracionesSliderBannerHomeAppimageUpload } from '../../components/admin/configuraciones/slider-banner-home/appimage-upload.vue'
export { default as AdminConfiguracionesSucursalesSucursalPreview } from '../../components/admin/configuraciones/sucursales/sucursal.preview.vue'
export { default as AdminConfiguracionesSucursalesSucursalRow } from '../../components/admin/configuraciones/sucursales/sucursal.row.vue'
export { default as AdminConfiguracionesSucursales } from '../../components/admin/configuraciones/sucursales/sucursales.vue'
export { default as AdminConfiguracionesTextosBarraNegraTextRow } from '../../components/admin/configuraciones/textos-barra-negra/text-row.vue'
export { default as AdminConfiguracionesTextosBarraNegra } from '../../components/admin/configuraciones/textos-barra-negra/textos-barra-negra.vue'
export { default as AdminEstadisticasCancelados } from '../../components/admin/estadisticas/cancelados/cancelados.vue'
export { default as AdminEstadisticasCanceladosMonthByDelivery } from '../../components/admin/estadisticas/cancelados/month-by-delivery.vue'
export { default as AdminEstadisticasCanceladosMonthGraph } from '../../components/admin/estadisticas/cancelados/month-graph.vue'
export { default as AdminEstadisticasCanceladosMonth } from '../../components/admin/estadisticas/cancelados/month.vue'
export { default as AdminEstadisticasUsersChangePass } from '../../components/admin/estadisticas/users/changePass.vue'
export { default as AdminEstadisticasUsersDaily } from '../../components/admin/estadisticas/users/daily.vue'
export { default as AdminEstadisticasUsersList } from '../../components/admin/estadisticas/users/list.vue'
export { default as AdminEstadisticasUsersMonthly } from '../../components/admin/estadisticas/users/monthly.vue'
export { default as AdminEstadisticasUsers } from '../../components/admin/estadisticas/users/users.vue'
export { default as AdminEstadisticasVentasMonthByDelivery } from '../../components/admin/estadisticas/ventas/month-by-delivery.vue'
export { default as AdminEstadisticasVentasMonthGraph } from '../../components/admin/estadisticas/ventas/month-graph.vue'
export { default as AdminEstadisticasVentasMonth } from '../../components/admin/estadisticas/ventas/month.vue'
export { default as AdminEstadisticasVentas } from '../../components/admin/estadisticas/ventas/ventas.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
