export type ComponentName = 'header'
    | 'modal'
    | 'bouncer'
    | 'cartPage'
    | 'homePage'
    | 'categoryPage'
    | 'cartButtons'
    | 'cartForm'
    | 'cartHeader'
    | 'cartList'
    | 'cartThx'
    | 'categoryGrid'
    | 'productCardButton'
    | 'productCard'
    | 'productGrid'
    | 'headerSocial';